name: Build ImmortalWRT Firmware

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential zstd

    - name: Download ImmortalWRT ImageBuilder
      run: |
        wget https://downloads.immortalwrt.org/releases/24.10.0/targets/x86/64/immortalwrt-imagebuilder-24.10.0-x86-64.Linux-x86_64.tar.zst
        tar --use-compress-program=unzstd -xvf immortalwrt-imagebuilder-24.10.0-x86-64.Linux-x86_64.tar.zst

    - name: Copy configuration files
      run: |
        cp .config immortalwrt-imagebuilder-24.10.0-x86-64/.config
        cp feeds immortalwrt-imagebuilder-24.10.0-x86-64/feeds.conf.default

    #- name: Install custom packages
    #  run: |
    #    cd immortalwrt-imagebuilder-24.10.0-x86-64
    #    make package/feeds/packages/<your-custom-package>/install V=s

    - name: Build firmware
      run: |
        cd immortalwrt-imagebuilder-24.10.0-x86-64
        make image V=s

    - name: Upload firmware
      uses: actions/upload-artifact@v2
      with:
        name: ImmortalWRT-Firmware
        path: immortalwrt-imagebuilder-24.10.0-x86-64/bin/targets/x86/64/
