name: ImmortalWrt x86_64 Builder

on:
  workflow_dispatch:
  push:
    paths:
      - '.config'
      - 'feeds.conf*'

env:
  CCACHE_DIR: ${{ github.workspace }}/ccache
  DL_DIR: ${{ github.workspace }}/dl
  TARGET: x86_64
  BUILD_JOBS: 4

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
    # ---------- 代码仓库初始化 ----------
    - name: Checkout base repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 1

    # ---------- 源码树准备 ----------
    - name: Prepare ImmortalWrt source
      id: prepare_source
      run: |
        # 选择其中一种源码获取方式（推荐方案A）
        
        # 方案A：使用子模块
        if [ -f .gitmodules ]; then
          git submodule update --init --recursive --depth=1
        else
          echo "::warning::Missing .gitmodules, cloning manually..."
          git clone https://github.com/immortalwrt/immortalwrt.git --depth=1
        fi

        # 方案B：强制覆盖式克隆（如果已有问题）
        # rm -rf immortalwrt
        # git clone https://github.com/immortalwrt/immortalwrt.git --depth=1

        # 验证目录结构
        if [ ! -d "immortalwrt" ]; then
          echo "::error::immortalwrt directory not found!"
          exit 1
        fi

    # ---------- 系统资源准备 ----------
    - name: Setup swap space (8GB)
      run: |
        sudo dd if=/dev/zero of=/swapfile bs=1M count=8192
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile

    # ---------- 依赖安装 ----------
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential ccache ecj fastjar file flex g++ gawk gettext \
          git libelf-dev libncurses5-dev libssl-dev python3 python3-pip \
          rsync unzip wget zlib1g-dev jq

    # ---------- 配置注入 ----------
    - name: Deploy configurations
      run: |
        echo "当前工作目录: $(pwd)"
        ls -al
        
        echo "正在注入配置文件..."
        cp -v .config immortalwrt/.config || echo "::warning::.config 文件不存在"
        cp -v feeds.conf* immortalwrt/ || echo "::warning::feeds.conf 文件不存在"
        
        # 配置文件存在性验证
        if [ ! -f "immortalwrt/.config" ]; then
          echo "::error::Missing .config in source directory!"
          exit 1
        fi

    # ---------- 编译环境准备 ----------
    - name: CCache configuration
      run: |
        sudo mkdir -p $CCACHE_DIR
        sudo chmod -R 777 $CCACHE_DIR
        ccache -M 5G
        ccache -s

    # ---------- 核心编译流程 ----------
    - name: Build system preparation
      working-directory: ./immortalwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig
        make -j$BUILD_JOBS download

    - name: Compile firmware
      working-directory: ./immortalwrt
      run: |
        make -j$BUILD_JOBS V=s || make -j1 V=s

    # ---------- 产物处理 ----------
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: immortalwrt-${{ github.run_id }}
        path: |
          ./immortalwrt/bin/targets/x86/64/*
          !**/*.manifest
          !**/*.sha256sum
