name: Build ImmortalWrt x86_64

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      extra_packages:
        description: 'Extra packages (space-separated)'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGEBUILDER_URL: https://downloads.immortalwrt.org/releases/24.10.0/targets/x86/64/immortalwrt-imagebuilder-24.10.0-x86-64.Linux-x86_64.tar.zst
      TARGET: x86/64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libncurses-dev \
          zlib1g-dev \
          gawk \
          git \
          gettext \
          libssl-dev \
          xsltproc \
          wget \
          unzip \
          zstd

    - name: Download and extract imagebuilder
      run: |
        wget $IMAGEBUILDER_URL -O imagebuilder.tar.zst
        mkdir imagebuilder
        tar -xaf imagebuilder.tar.zst -C imagebuilder --strip-components 1

    - name: Copy configuration files
      run: |
        cp -v .config imagebuilder/
        cp -v feeds.conf.default imagebuilder/

    - name: Prepare build environment
      working-directory: ./imagebuilder
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig

    - name: Build image
      working-directory: ./imagebuilder
      run: |
        EXTRA_PACKAGES="${{ github.event.inputs.extra_packages }}"
        make image \
          PROFILE="generic" \
          PACKAGES="base-files $EXTRA_PACKAGES" \
          FILES="files"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4  # 关键修正点
      with:
        name: immortalwrt-binaries
        path: imagebuilder/bin/targets/$TARGET/*.gz
