name: Build ImmortalWRT

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # 根据构建需要调整超时时间

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libssl-dev \
          zstd \
          python3 \
          file \
          wget

    - name: Download Image Builder
      run: wget https://downloads.immortalwrt.org/releases/24.10.0/targets/x86/64/immortalwrt-imagebuilder-24.10.0-x86-64.Linux-x86_64.tar.zst

    - name: Extract Image Builder
      run: tar -I zstd -xf immortalwrt-imagebuilder-*.tar.zst

    - name: Prepare configuration
      run: |
        # 将仓库中的.config文件复制到镜像构建器目录
        cp path/to/your/config/.config immortalwrt-imagebuilder-*/  # 修改为你的实际配置文件路径

    - name: Build firmware
      working-directory: ./immortalwrt-imagebuilder-24.10.0-x86-64.Linux-x86_64  # 根据实际目录名调整
      run: |
        make -j$(nproc) image \
          PROFILE="generic" \
          FILES="$PWD/files" \
          PACKAGES="$(cat packages.txt)"  # 如果有自定义包列表

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: immortalwrt-firmware
        path: |
          ./immortalwrt-imagebuilder-24.10.0-x86-64.Linux-x86_64/bin/targets/x86/64/*.img.gz
          ./immortalwrt-imagebuilder-24.10.0-x86-64.Linux-x86_64/bin/targets/x86/64/sha256sums
